### ISSUE TITLE
Possible typo in diagram?

### ISSUE THREAD

**Issue by sylph01** [ekr/mls-protocol#47]
Please correct me if my understanding is wrong:

* The diagram of "user-initiated join" shows `UserAdd(.->D)` and `state.add(D)` initiated by user `Z`. Isn't it `UserAdd(.->Z)` and `state.add(Z)`?
* The diagram of Update shows `Update(A)` message from server telling A and B to `state.upd(D)` and Z to `state.upd(A)`. Shouldn't all of them be `state.upd(A)`, because A initiated the update?

**Comment by josephlhall** [comment]
+1 I was going to fix this with a PR today but some of these ladder diagrams are just mysterious enough to make it probably something @bifurcation should look at in his copious free time.

**Comment by beurdouche** [comment]
Fixed in https://github.com/ekr/mls-protocol/commit/c81dd324d4e8a894766d5965c78f6d4ad68907ad
Thanks
